
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA ID NORMSTRING NUMBER TCARNET TDESCRIPCION TDIA TESTADO TFECHA THORA TMATERIA TMES TNOMBREstatement : dato COMA dato COMA dato COMA dato COMA dato COMA dato COMA dato COMA dato COMA datodato : NORMSTRING\n            | NUMBER\n\n\n    '
    
_lr_action_items = {'NORMSTRING':([0,5,7,9,11,13,15,17,19,],[3,3,3,3,3,3,3,3,3,]),'NUMBER':([0,5,7,9,11,13,15,17,19,],[4,4,4,4,4,4,4,4,4,]),'$end':([1,3,4,20,],[0,-2,-3,-1,]),'COMA':([2,3,4,6,8,10,12,14,16,18,],[5,-2,-3,7,9,11,13,15,17,19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'dato':([0,5,7,9,11,13,15,17,19,],[2,6,8,10,12,14,16,18,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> dato COMA dato COMA dato COMA dato COMA dato COMA dato COMA dato COMA dato COMA dato','statement',17,'p_statement_separacioncomas','sintacticot5.py',8),
  ('dato -> NORMSTRING','dato',1,'p_dato','sintacticot5.py',24),
  ('dato -> NUMBER','dato',1,'p_dato','sintacticot5.py',25),
]
